nmHoistingLimits: none

nodeLinker: node-modules

packageExtensions:
  "@blueprintjs/popover2@*":
    peerDependencies:
      react-dom: "*"
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    dependencies:
      typescript: "*"
  "@mdx-js/loader@*":
    peerDependencies:
      react: "*"
  apollo-codegen-flow@*:
    dependencies:
      graphql: "*"
  apollo-codegen-scala@*:
    dependencies:
      graphql: "*"
  apollo-codegen-swift@*:
    dependencies:
      graphql: "*"
  apollo-codegen-typescript@*:
    dependencies:
      graphql: "*"
  apollo-link-context@*:
    peerDependencies:
      graphql: "*"
  apollo-link-error@*:
    peerDependencies:
      graphql: "*"
  babel-plugin-graphql-tag@*:
    dependencies:
      graphql: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  eslint-plugin-prettier@*:
    dependencies:
      eslint-config-prettier: "*"
  graphql.macro@*:
    dependencies:
      "@babel/core": "*"
      "@babel/runtime": "*"
      graphql: "*"
  react-dev-utils@*:
    peerDependencies:
      typescript: "*"
      webpack: "*"
  styled-components@*:
    dependencies:
      babel-plugin-macros: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
