{{- if and (.Values.ingress.enabled) (.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dagster.fullname" . }}-ingress
  labels:
    {{- include "dagster.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | squote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
    {{- if .Values.ingress.dagit.tls.enabled }}
    - hosts:
        - {{ .Values.ingress.dagit.host }}
      secretName: {{ .Values.ingress.dagit.tls.secretName }}
    {{- end }}
    {{- if .Values.ingress.readOnlyDagit.tls.enabled }}
    - hosts:
        - {{ .Values.ingress.readOnlyDagit.host }}
      secretName: {{ .Values.ingress.readOnlyDagit.tls.secretName }}
    {{- end }}
    {{- if .Values.ingress.flower.tls.enabled }}
    - hosts:
        - {{ .Values.ingress.flower.host }}
      secretName: {{ .Values.ingress.flower.tls.secretName }}
    {{- end }}
  rules:
    - host: {{ .Values.ingress.dagit.host }}
      http:
        paths:
          {{- range .Values.ingress.dagit.precedingPaths }}
          - path: {{ .path }}
            pathType: {{ $dagitPathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  {{- include "ingress.service.port" . | indent 16 }}
          {{- end }}
          - path: {{ .Values.ingress.dagit.path | default "/*" }}
            pathType: {{ $dagitPathType }}
            backend:
              service:
                name: {{ include "dagster.dagit.fullname" . }}
                port:
                  number: {{ .Values.dagit.service.port | default 80 }}
          {{- range .Values.ingress.dagit.succeedingPaths }}
          - path: {{ .path }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  {{- include "ingress.service.port" . | indent 16 }}
          {{- end }}
    {{- if .Values.dagit.enableReadOnly }}
    - host: {{ .Values.ingress.readOnlyDagit.host }}
      http:
        paths:
          {{- range .Values.ingress.readOnlyDagit.precedingPaths }}
          - path: {{ .path }}
            pathType: {{ $readOnlyDagitPathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  {{- include "ingress.service.port" . | indent 16 }
          {{- end }}
          - path: {{ .Values.ingress.readOnlyDagit.path | default "/*" }}
            pathType: {{ $readOnlyDagitPathType }}
            backend:
              service:
                name: {{ template "dagster.dagit.fullname" dict "Values" .Values "Release" .Release "dagitReadOnly" true }}
                port:
                  number: {{ .Values.dagit.service.port | default 80 }}
          {{- range .Values.ingress.readOnlyDagit.succeedingPaths }}
          - path: {{ .path }}
            pathType: {{ $readOnlyDagitPathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  {{- include "ingress.service.port" . | indent 16 }}
          {{- end }}
    {{end}}
    {{- if .Values.flower.enabled }}
    - host: {{ .Values.ingress.flower.host }}
      http:
        paths:
          {{- range .Values.ingress.flower.precedingPaths }}
          - path: {{ .path }}
            pathType: {{ $flowerPathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  {{- include "ingress.service.port" . | indent 16 }}
          {{- end }}
          - path: {{ .Values.ingress.flower.path | default "/*" }}
            pathType: {{ $flowerPathType }}
            backend:
              service:
                name: {{ template "dagster.fullname" . }}-flower-service
                port:
                  number: {{ .Values.flower.service.port }}
          {{- range .Values.ingress.flower.succeedingPaths }}
          - path: {{ .path }}
            pathType: {{ $flowerPathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  {{- include "ingress.service.port" . | indent 16 }}
          {{- end }}
    {{end}}
{{end}}
